/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlinefooddelivery;


import com.mysql.jdbc.PreparedStatement;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Onlinefooddelivery.DBConnection;

/**
 *
 * @author Yray
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public Login() {
        initComponents();
      
        this.close.setVisible(false);
        this.setLocationRelativeTo(null);
        setIconImage();
        this.setResizable(false);
        setTitle("SILOG NI NANARD");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        jTextField_Username = new javax.swing.JTextField();
        passwordfieldlogin = new javax.swing.JPasswordField();
        Logo = new javax.swing.JLabel();
        open = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        signupbutton = new javax.swing.JButton();
        Signintext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginPanel.setBackground(new java.awt.Color(204, 204, 255));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });
        LoginPanel.add(jTextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 170, 30));

        passwordfieldlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldloginActionPerformed(evt);
            }
        });
        LoginPanel.add(passwordfieldlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 170, 30));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinefooddelivery/SILOG NI NANARDS.png"))); // NOI18N
        LoginPanel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 250, -1));

        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinefooddelivery/openpinakafinal.png"))); // NOI18N
        open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openMousePressed(evt);
            }
        });
        LoginPanel.add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, 20));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinefooddelivery/finalclose.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        LoginPanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        username.setText("Username");
        LoginPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel1.setText("Password");
        LoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        loginbutton.setBackground(new java.awt.Color(51, 51, 255));
        loginbutton.setText("Log in");
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbuttonMouseClicked(evt);
            }
        });
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        LoginPanel.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        signupbutton.setBackground(new java.awt.Color(51, 51, 255));
        signupbutton.setText("Sign up");
        signupbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupbuttonMouseClicked(evt);
            }
        });
        LoginPanel.add(signupbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        Signintext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Signintext.setText("Sign In");
        LoginPanel.add(Signintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    private void openMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMousePressed
        close.setVisible(true);
        open.setVisible(false);
        passwordfieldlogin.setEchoChar((char)0);
    }//GEN-LAST:event_openMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        open.setVisible(true);
        close.setVisible(false);
        passwordfieldlogin.setEchoChar('*');
    }//GEN-LAST:event_closeMousePressed

    private void signupbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupbuttonMouseClicked
        Signup s = new Signup();
        s.setVisible(true);
        s.pack();
        s.setLocationRelativeTo(null);
        s.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_signupbuttonMouseClicked

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed

        java.sql.PreparedStatement st;
        ResultSet rs;

        // for username and password
        String username = jTextField_Username.getText();
        String password = String.valueOf(passwordfieldlogin.getPassword());

        // query to check if the account exist in the database

        String query = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";

        try {
            st  = DBConnection.getConnection().prepareStatement(query);

            st.setString(1, username);
            st.setString(2, password);

            rs = st.executeQuery();

            if (rs.next())
            {
                // this will show the Main Menu
                Mainscreen m = new Mainscreen();
                m.setVisible(true);
                m.pack();
                m.setLocationRelativeTo(null);
                m.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
                this.dispose();
            } else{
                JOptionPane.showMessageDialog(null,"Invalid Username / Password", "Login Error",2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
        
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void passwordfieldloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldloginActionPerformed

    private void loginbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseClicked
      
    }//GEN-LAST:event_loginbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Signintext;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField_Username;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel open;
    private javax.swing.JPasswordField passwordfieldlogin;
    private javax.swing.JButton signupbutton;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
