/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlinefooddelivery;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Toolkit;

/**
 *
 * @author Bularon,Yray,Kaamino
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage();
        this.setResizable(false);
        setTitle("SILOG NI NANARD");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstnamefield = new javax.swing.JTextField();
        lastnamefield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        phonenumberfield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        passwordfieldsignup = new javax.swing.JTextField();
        firstnamelabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        phonenumberlabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        createanaccountlabel = new javax.swing.JLabel();
        signupbutton = new javax.swing.JButton();
        backbuttonlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        phonenumberfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonenumberfieldKeyTyped(evt);
            }
        });

        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });

        firstnamelabel.setText("First Name");

        lastnamelabel.setText("Last Name");

        addresslabel.setText("Address");

        phonenumberlabel.setText("Phone Number");

        emaillabel.setText("Username");

        passwordlabel.setText("Password");

        createanaccountlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createanaccountlabel.setText("Create an Account");

        signupbutton.setBackground(new java.awt.Color(51, 51, 255));
        signupbutton.setText("Sign Up");
        signupbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupbuttonMouseClicked(evt);
            }
        });
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });

        backbuttonlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinefooddelivery/backbutton.png"))); // NOI18N
        backbuttonlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backbuttonlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordlabel)
                            .addComponent(emaillabel)
                            .addComponent(phonenumberlabel)
                            .addComponent(addresslabel)
                            .addComponent(lastnamelabel)
                            .addComponent(firstnamelabel)
                            .addComponent(firstnamefield)
                            .addComponent(emailfield)
                            .addComponent(passwordfieldsignup)
                            .addComponent(phonenumberfield)
                            .addComponent(addressfield)
                            .addComponent(lastnamefield)
                            .addComponent(createanaccountlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(signupbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createanaccountlabel)
                    .addComponent(backbuttonlabel))
                .addGap(18, 18, 18)
                .addComponent(firstnamelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lastnamelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(addresslabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phonenumberlabel)
                .addGap(12, 12, 12)
                .addComponent(phonenumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(emaillabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(passwordlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordfieldsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupbutton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void backbuttonlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonlabelMouseClicked
        Login l = new Login();
        l.setVisible(true);
        l.pack();
        l.setLocationRelativeTo(null);
        l.setDefaultCloseOperation(Signup.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backbuttonlabelMouseClicked

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        String fname = firstnamefield.getText();
        String lname = lastnamefield.getText();
        String username = emailfield.getText();
        String address = addressfield.getText();
        String phonenumber = phonenumberfield.getText();
        String pass1 = String.valueOf(passwordfieldsignup.getText());
        {
        }
        if (verifyFields())
        {
            if(!checkUsername(username))
            {
               PreparedStatement ps;
               ResultSet rs;
                String registerUserQuery = "INSERT INTO `users`(`fname`, `lname`, `username`, `password`, `address`, `phonenumber`) VALUES (?,?,?,?,?,?)";
                
                try {
                    ps = DBConnection.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1,fname);
                    ps.setString(2,lname);
                    ps.setString(3,username);
                    ps.setString(4,pass1);
                    ps.setString(5, address);
                    ps.setString(6, phonenumber);
                    
                    
                    
                    ps.setNull(6, java.sql.Types.NULL);
                    
                    if (ps.executeUpdate() !=0){
                        JOptionPane.showMessageDialog(null,"Your Account Has been created");
                    }else{
                        JOptionPane.showMessageDialog(null,"Error: Please Check Your information");
                    }
                    
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                
                
                
                
            }
        }
    }//GEN-LAST:event_signupbuttonActionPerformed
 //log out
    private void signupbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupbuttonMouseClicked
      Login l = new Login();
        l.setVisible(true);
        l.pack();
        l.setLocationRelativeTo(null);
        l.setDefaultCloseOperation(Signup.EXIT_ON_CLOSE);
        this.dispose();      
    }//GEN-LAST:event_signupbuttonMouseClicked
//allow only numbers
    private void phonenumberfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenumberfieldKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
        evt.consume();
         }
        
    }//GEN-LAST:event_phonenumberfieldKeyTyped
        // fuction to verify empty fields
    public boolean verifyFields(){
        String fname = firstnamefield.getText();
        String lname = lastnamefield.getText();
        String uname = emailfield.getText();
        String pass1 = String.valueOf(passwordfieldsignup.getText());
        ;
        
       
        // will check empty fields
        if (fname.trim().equals("") || lname.trim().equals("")
            || uname.trim().equals("") || pass1.trim().equals(""))
        {
        JOptionPane.showMessageDialog(null,"There are one or more fields Empty", "Empty Fields",2);
        return false;
        }
        // when everything is fine
        else{
            return true;
        }
    }
    // a function that check if username is exist in the dbs
    public boolean checkUsername(String username){
        
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM `login` WHERE `username` =?";
        
        try {
            st = DBConnection.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                username_exist = true;
                JOptionPane.showMessageDialog(null,"The Username is taken, Please Choose Another Username", "Username Failed",2);
            }
           
            
            
            
        } catch (SQLException ex) {
           Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        
        return username_exist;
        
    }// create a function to verify empty fields

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JLabel backbuttonlabel;
    private javax.swing.JLabel createanaccountlabel;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JTextField passwordfieldsignup;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JTextField phonenumberfield;
    private javax.swing.JLabel phonenumberlabel;
    private javax.swing.JButton signupbutton;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
